MvcOnlineTicariOtomasyon/Models/Class/SalesAction.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MvcOnlineTicariOtomasyon.Models.Class
{
    public class SalesAction
    {
        [Key]
        public int SaleId { get; set; }
        public DateTime Date { get; set; }
        public int Piece { get; set; }
        public decimal Price { get; set; }
        public decimal TotalAmount { get; set; }

        public int ProductId { get; set; }

        public int StaffId { get; set; }
        public int CustomerId { get; set; }

        public virtual Product Product { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Staff Staff { get; set; }



    }
}

MvcOnlineTicariOtomasyon/Controllers/SaleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcOnlineTicariOtomasyon.Models.Class;

namespace MvcOnlineTicariOtomasyon.Controllers
{
    public class SaleController : Controller
    {
        // GET: Expense

        Context context = new Context();
        public ActionResult Index()
        {
            var degerler = context.SalesActions.ToList();
            return View(degerler);
        }
        [HttpGet]
        public ActionResult YeniSatis()
        {
            List<SelectListItem> deger1 = (from x in context.Products.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.ProductName,
                                               Value = x.ProductId.ToString()
                                           }).ToList();

            List<SelectListItem> deger2 = (from x in context.Customers.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.CustomerName+ " "+ x.CustomerSurname,
                                               Value = x.CustomerId.ToString()
                                           }).ToList();

            List<SelectListItem> deger3 = (from x in context.Staffs.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.StaffName + " " + x.StaffSurname,
                                               Value = x.StaffId.ToString()
                                           }).ToList();


            ViewBag.dgr1 = deger1;
            ViewBag.dgr2 = deger2;
            ViewBag.dgr3 = deger3;
            return View();
        }
        [HttpPost]
        public ActionResult YeniSatis(SalesAction salesAction)
        {
            salesAction.Date =DateTime.Parse(DateTime.Now.ToShortDateString());
            context.SalesActions.Add(salesAction);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult SatisGetir(int id)
        {
            List<SelectListItem> deger1 = (from x in context.Products.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.ProductName,
                                               Value = x.ProductId.ToString()
                                           }).ToList();

            List<SelectListItem> deger2 = (from x in context.Customers.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.CustomerName + " " + x.CustomerSurname,
                                               Value = x.CustomerId.ToString()
                                           }).ToList();

            List<SelectListItem> deger3 = (from x in context.Staffs.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.StaffName + " " + x.StaffSurname,
                                               Value = x.StaffId.ToString()
                                           }).ToList();


            ViewBag.dgr1 = deger1;
            ViewBag.dgr2 = deger2;
            ViewBag.dgr3 = deger3;

            var deger = context.SalesActions.Find(id);
            return View("SatisGetir",deger);
        }

        public ActionResult SatisGuncelle(SalesAction sale)
        {
            var deger = context.SalesActions.Find(sale.SaleId);
            deger.CustomerId = sale.CustomerId;
            deger.Piece = sale.Piece;
            deger.Price = sale.Piece;
            deger.StaffId = sale.StaffId;
            deger.Date = sale.Date;
            deger.TotalAmount = sale.TotalAmount;
            deger.ProductId = sale.ProductId;
            context.SaveChanges();
            return RedirectToAction("Index");
 
        }

        public ActionResult SatisDetay(int id)
        {
            var degerler = context.SalesActions.Where(x => x.SaleId == id).ToList();
            return View(degerler); 
        }


    }
}

MvcOnlineTicariOtomasyon/Views/Sale/Index.cshtml
@using MvcOnlineTicariOtomasyon.Models.Class;
@model List<SalesAction>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<table id="tbl1" class="table table-bordered" style="margin-top:20px;">
    <thead>
        <tr>
            <th>ID</th>
            <th>Ürün</th>
            <th>Müşteri</th>
            <th>Personel</th>
            <th>Adet</th>
            <th>Fiyat</th>
            <th>Toplam</th>
            <th>Tarih</th>
            <th>Güncelle</th>
            <th>Detaylar</th>
        </tr>
    </thead>
    @foreach (var sa in Model)
    {
        <tr>
            <td>@sa.SaleId</td>
            <td>
                @sa.Product.ProductName
            </td>
            <td>@sa.Customer.CustomerName @sa.Customer.CustomerSurname</td>
            <td>@sa.Staff.StaffName @sa.Staff.StaffSurname</td>
            <td>@sa.Piece</td>
            <td>@sa.Price</td>
            <td>@sa.TotalAmount</td>
            <td>@sa.Date</td>

            <td>
                <a href="/Sale/SatisGetir/@sa.SaleId" class="btn btn-success">Güncelle</a>
            </td>
            <td>
                <a href="/Sale/SatisDetay/@sa.SaleId" class="btn btn-warning">Detay</a>
            </td>

        </tr>
    }

</table>
<a href="/Sale/YeniSatis" class="btn btn-primary">Yeni Satış Yap</a>
<!--Jquery Script-->
<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/1.10.22/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.22/js/dataTables.bootstrap4.min.js"></script>

<script>
    $('#tbl1').dataTable({
        "language": {

            "url": "//cdn.datatables.net/plug-ins/1.10.12/i18n/Turkish.json"

        }
    });
</script>

MvcOnlineTicariOtomasyon/Views/Sale/SatisDetay.cshtml
@using MvcOnlineTicariOtomasyon.Models.Class
@model List<SalesAction>
@{
    ViewBag.Title = "SatisDetay";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h2>Satış Detayları</h2>
<br />
<table class="table table-condensed">
    <tr>
        <th>Satış Id</th>
        <th>Ürün</th>
        <th>Müşteri</th>
        <th>Personel</th>
        <th>Fiyat</th>
        <th>Adet</th>
        <th>Toplam</th>
        <th>Tarih</th>
    
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.SaleId</td>
            <td>@item.Product.ProductName</td>
            <td>@item.Customer.CustomerName @item.Customer.CustomerSurname</td>
            <td>@item.Staff.StaffSurname @item.Staff.StaffSurname</td>
            <td>@item.Price</td>
            <td>@item.Piece</td>
            <td>@item.TotalAmount</td>
            <td>@item.Date</td>
            
        </tr>
    }

</table>
<button class="btn btn-primary">Yazdır</button>

MvcOnlineTicariOtomasyon/Views/Sale/SatisGetir.cshtml
@model MvcOnlineTicariOtomasyon.Models.Class.SalesAction
@{
    ViewBag.Title = "SatisGetir";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Satış Güncelleme Sayfası</h2>

@using (Html.BeginForm("SatisGuncelle", "Sale", FormMethod.Post))
{
    @Html.HiddenFor(x=>x.SaleId)
    @Html.LabelFor(x => x.Product)
    @Html.DropDownListFor(x => x.ProductId, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Customer)
    @Html.DropDownListFor(x => x.CustomerId, (List<SelectListItem>)ViewBag.dgr2, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Staff)
    @Html.DropDownListFor(x => x.StaffId, (List<SelectListItem>)ViewBag.dgr3, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Piece)
    @Html.TextBoxFor(x => x.Piece, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Price)
    @Html.TextBoxFor(x => x.Price, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.TotalAmount)
    @Html.TextBoxFor(x => x.TotalAmount, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Date)
    @Html.TextBoxFor(x => x.Date, new { @class = "form-control" })
    <br />
    <button class="btn btn-warning">Güncelle</button>

}

MvcOnlineTicariOtomasyon/Views/Sale/YeniSatis.cshtml
@model MvcOnlineTicariOtomasyon.Models.Class.SalesAction
@{
    ViewBag.Title = "YeniSatis";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h2>Yeni Satış Sayfası</h2>
<br />
<form class="form-group" method="post">
    @Html.LabelFor(x => x.Product)
    @Html.DropDownListFor(x => x.ProductId, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Customer)
    @Html.DropDownListFor(x => x.CustomerId, (List<SelectListItem>)ViewBag.dgr2, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Staff)
    @Html.DropDownListFor(x => x.StaffId, (List<SelectListItem>)ViewBag.dgr3, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Piece)
    @Html.TextBoxFor(x => x.Piece, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Price)
    @Html.TextBoxFor(x => x.Price, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.TotalAmount)
    @Html.TextBoxFor(x => x.TotalAmount, new { @class = "form-control" })
    <br />

    <button class="btn btn-primary">Satış Yap</button>
</form>